### ISSUE TITLE
Feedback for “Knowledge Base”

### ISSUE THREAD

**Issue by WiredContact** [botpress/documentation#144]
The term "small talk" which is a feature does not appear to be supported by a KB article. 
I was looking for the correct way to list out questions and answers on a webpage.

Have to say I am very impressed with what I have found so far
thank you
Paul

**Comment by devguilhermy** [comment]
Hey @WiredContact, thanks for pointing this out!

The Smalltalk feature has been deprecated, that's why it's not documented. In order to have you bot answer to simple questions like Hey, How are you, etc, just write the questions and answers in a plain text document. It's gonna behave the same way.

If you have other questions or need something else please go to our [Discord server](https://discord.gg/botpress), our community would be happy to help!
